const questions = [
  {
    id: 0,
    content: "みんなと話すのが楽しいと思います。",
    type: "E/I",
    score: 1,
  },
  {
    id: 1,
    content: "細かい作業に集中するのが得意です。",
    type: "S/N",
    score: 1,
  },
  {
    id: 2,
    content: "人の気持ちをよく理解できる方だと思います。",
    type: "F/T",
    score: 1,
  },
  {
    id: 3,
    content: "予定通りに物事を進めるのが好きです。",
    type: "J/P",
    score: 1,
  },
  {
    id: 4,
    content: "知らない人と話すのに抵抗はありません。",
    type: "E/I",
    score: 1,
  },
  {
    id: 5,
    content: "物事を考える時、直感よりも事実を重視します。",
    type: "S/N",
    score: 1,
  },
  {
    id: 6,
    content: "決める時に感情が判断に影響することが多いです。",
    type: "F/T",
    score: 1,
  },
  {
    id: 7,
    content: "何かを始める前に計画を立てるのが好きです。",
    type: "J/P",
    score: 1,
  },
  {
    id: 8,
    content: "賑やかな場所にいるとエネルギーが湧きます。",
    type: "E/I",
    score: 1,
  },
  {
    id: 9,
    content: "日常生活の中で細部に気を配ることが得意です。",
    type: "S/N",
    score: 1,
  },
  {
    id: 10,
    content: "人の感情に共感しやすい方です。",
    type: "F/T",
    score: 1,
  },
  {
    id: 11,
    content: "自由に動くよりも、計画通りに動く方が好きです。",
    type: "J/P",
    score: 1,
  },
  {
    id: 12,
    content: "大勢の人の中でも緊張せずに話せます。",
    type: "E/I",
    score: 1,
  },
  {
    id: 13,
    content: "新しいことを学ぶ時、理論よりも実践を好みます。",
    type: "S/N",
    score: 1,
    },
  {
    id: 14,
    content: "友達の悩みを聞く時、感情に寄り添うことが多いです。",
    type: "F/T",
    score: 1,
  },
  {
    id: 15,
    content: "ルールがある方が安心して行動できます。",
    type: "J/P",
    score: 1,
  },
  {
    id: 16,
    content: "話題が盛り上がると自分の意見を積極的に話します。",
    type: "E/I",
    score: 1,
  },
  {
    id: 17,
    content: "未来の可能性について考えるのが好きです。",
    type: "S/N",
    score: -1,
    },
  {
    id: 18,
    content: "物事を決める時、論理的に考える方です。",
    type: "F/T",
    score: -1,
    },
  {
    id: 19,
    content: "急な予定変更よりも、予定通りに進む方が落ち着きます。",
    type: "J/P",
    score: 1,
    },
  {
    id: 20,
    content: "イベントで司会やリーダーを引き受けるのが得意です。",
    type: "E/I",
    score: 1,
    },
  {
    id: 21,
    content: "物事を分析するとき、具体的なデータを大事にします。",
    type: "S/N",
    score: 1,
  },
  {
    id: 22,
    content: "誰かを励ます時、気持ちを重視して言葉を選びます。",
    type: "F/T",
    score: 1,
  },
  {
    id: 23,
    content: "ゴールが明確でないと、落ち着かない方です。",
    type: "J/P",
    score: 1,
  },
  {
    id: 24,
    content: "活発なグループの中で自分の存在感を発揮できます。",
    type: "E/I",
    score: 1,
  },
  {
    id: 25,
    content: "新しいアイデアを考えるのが楽しいです。",
    type: "S/N",
    score: -1,
    },
  {
    id: 26,
    content: "周りの状況よりも、自分の考えに集中することが多いです。",
    type: "F/T",
    score: -1,
  },
  {
    id: 27,
    content: "予定がない日は不安になります。",
    type: "J/P",
    score: 1,
  },
  {
    id: 28,
    content: "休みの日でも外出して人と会いたいと思います。",
    type: "E/I",
    score: 1,
  },
  {
    id: 29,
    content: "抽象的なテーマについて話し合うのが得意です。",
    type: "S/N",
    score: -1,
  },
  {
    id: 30,
    content: "他人よりも自分の価値観を優先することが多いです。",
    type: "F/T",
    score: -1,
  },
  {
    id: 31,
    content: "やるべきことをリスト化するのが好きです。",
    type: "J/P",
    score: 1,
  },
  {
    id: 32,
    content: "誰とでもすぐに打ち解けられる方だと思います。",
    type: "E/I",
    score: 1,
  },
  {
    id: 33,
    content: "事実よりも可能性を追求する方が好きです。",
    type: "S/N",
    score: -1,
  },
  {
    id: 34,
    content: "自分の気持ちよりも周りの意見を優先することが多いです。",
    type: "F/T",
    score: 1,
  },
  {
    id: 35,
    content: "スケジュール通りに物事を進めると安心します。",
    type: "J/P",
    score: 1,
  },
];
